apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fake-project.fullname" . }}
  labels:
    {{- include "fake-project.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fake-project.selectorLabels" . | nindent 6 }}
      role: app
  template:
    metadata:
      labels:
        {{- include "fake-project.selectorLabels" . | nindent 8 }}
        role: app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.app.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
