kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress-in-ns
spec:
  podSelector:
    matchLabels:
      {{- include "fake-project.selectorLabels" . | nindent 6 }}
  ingress:
    - {}
