apiVersion: v1
kind: Service
metadata:
  name: {{ include "fake-project.fullname" . }}
  labels:
    {{- include "fake-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fake-project.selectorLabels" . | nindent 4 }}
    role: app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fake-project.fullname" . }}-wp
  labels:
  {{- include "fake-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wp.service.type }}
  ports:
    - port: {{ .Values.wp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fake-project.selectorLabels" . | nindent 4 }}
    role: wp
