{{- if .Values.wp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.wp.serviceAccount.name}}
  labels:
    {{- include "fake-project.labels" . | nindent 4 }}
  {{- with .Values.wp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.workload.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workload.serviceAccount.name}}
  labels:
  {{- include "fake-project.labels" . | nindent 4 }}
  {{- with .Values.workload.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
