# Default values for fake-project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

app:
  service:
    type: ClusterIP
    port: 8000
  image:
    repository: pabardina/gohostname
    pullPolicy: IfNotPresent
    tag: latest
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  resources:
    limits:
      cpu: 0.5
      memory: 500Mi
    requests:
      cpu: 0.2
      memory: 256Mi

wp:
  replicas: 1
  config:
    host: "fake-project-cloudsql-proxy"
    database: "app"
    password: "supersecret"
    username: "username"
    email: test@test.com
    firstname: first_name
    lastname: last_name
    blogName: Blog
  image:
    repository: bitnami/wordpress
    pullPolicy: IfNotPresent
    tag: 5
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 300Mi
  service:
    type: ClusterIP
    port: 8080
  serviceAccount:
    name: "ksa-app-cloudsql"
    create: true
    annotations:
      iam.gke.io/gcp-service-account: gke-cluster-sa-k8s-cloudsql@YOUR_PROJECT_ID.iam.gserviceaccount.com

workload:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - gpu
  bucket: "gke-cluster-subnet-test-quebec"
  image:
    repository: gcr.io/google.com/cloudsdktool/cloud-sdk
    pullPolicy: IfNotPresent
  serviceAccount:
    name: "ksa-app-gcs"
    create: true
    annotations:
      iam.gke.io/gcp-service-account: gke-cluster-sa-k8s-gcs@YOUR_PROJECT_ID.iam.gserviceaccount.com
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"

cloudSqlProxy:
  replicas: 3
  dbPort: 3306
  instanceConnectionName: "YOUR_PROJECT_ID:northamerica-northeast1:gke-cluster-sql-mysql-57"
  image:
    name: "gcr.io/cloudsql-docker/gce-proxy"
    version: "1.19.2"
